# This is used to manage Ansible role dependences
# http://docs.ansible.com/galaxy.html#installing-multiple-roles-from-a-file

- src: kurron.artifactory
- src: kurron.atlassian
- src: kurron.aws
- src: kurron.base
- src: kurron.block-device
- src: kurron.cpp-developer
- src: kurron.docker-host
- src: kurron.dsl-developer
- src: kurron.elastic-stack
- src: kurron.hashicorp
- src: kurron.javascript-developer
- src: kurron.jdk
- src: kurron.jvm-developer
- src: kurron.logfaces
- src: kurron.logstash
- src: kurron.mongodb
- src: kurron.mysql
- src: kurron.node-js
- src: kurron.operations
- src: kurron.os-limits
- src: kurron.php-developer
- src: kurron.plex
- src: kurron.python-developer
- src: kurron.rabbitmq
- src: kurron.redis
- src: kurron.resilio-sync
- src: kurron.rsync
- src: kurron.ruby-developer
- src: kurron.software-developer
- src: kurron.sql-developer
- src: kurron.time
- src: kurron.transparent-huge-pages
- src: kurron.virtualbox
