---
- name: Provision Desktop 
  hosts: localhost
  roles:
  - kurron.logfaces
  - kurron.atlassian
  - kurron.aws
  - kurron.docker-host
  - kurron.hashicorp
  - kurron.javascript-developer
  - kurron.jvm-developer
  - { role: kurron.operations, operations_loggly_install: false, operations_datadog_install: false }
  - kurron.python-developer
  - kurron.software-developer
  - kurron.sql-developer

